name: chart-base pipeline
trigger:
  branches:
    include:
      - refs/tags/*
pr:
  branches:
    include:
      - master

resources:
  repositories:
    - repository: cnp-library
      type: github
      ref: refs/heads/master
      name: hmcts/cnp-azuredevops-libraries
      endpoint: 'hmcts'

variables:
  - name: agentPool
    value: ubuntu-latest

jobs:
  - job: Validate
    pool:
      vmImage: ${{ variables.agentPool }}
    strategy:
      matrix:
        java:
          language: java
        nodejs:
          language: nodejs

    steps:
      - template: steps/charts/validate.yaml@cnp-library
        parameters:
          chartName: base
          chartReleaseName: chart-base-$(language)-ci-test
          chartNamespace: chart-tests
          helmInstallTimeout: "500"
          valuesFile: "ci-values-$(language).yaml"


  - job: Release
    # Make sure we have a tag to run this job
    condition: >
      and(
          succeeded(),
          startsWith(variables['Build.SourceBranch'], 'refs/tags/')
        )
    dependsOn: Validate
    pool:
      vmImage: ${{ variables.agentPool }}
    steps:
      - template: steps/charts/release.yaml@cnp-library
        parameters:
          chartName: base
          chartReleaseName: chart-base
          chartNamespace: chart-tests