apiVersion: v2
description: Base Helm chart for HMCTS Apps
name: base
# This is the chart version. This doesn't need to be incremented on every change.
# It is managed by release pipeline based on Github tag
version: 0.1.0 # Do not change
appVersion: 0.1.0 # Do not change
keywords:
  - base
sources:
  - https://github.com/hmcts/chart-base
icon: https://nodejs.org/static/images/logos/nodejs-new-pantone-black.png
dependencies:
  - name: library
    version: 0.4.3
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
