applicationPort: 3000
replicas: 1
useInterpodAntiAffinity: true
registerAdditionalDns:
  enabled: false
memoryRequests: 512Mi
cpuRequests: 25m
memoryLimits: 512Mi
cpuLimits: 500m
devmemoryRequests: 64Mi
devcpuRequests: 25m
devmemoryLimits: 512Mi
devcpuLimits: 500m
readinessPath: /health/readiness
readinessDelay: 0
readinessTimeout: 3
readinessPeriod: 15
livenessPath: /health/liveness
livenessDelay: 0
livenessTimeout: 3
livenessPeriod: 15
livenessFailureThreshold: 3
spotInstances:
  enabled: false
startupPath: /health/liveness
startupDelay: 5
startupTimeout: 3
startupPeriod: 10
startupFailureThreshold: 15
saEnabled: true
devApplicationInsightsInstrumentKey: '00000000-0000-0000-0000-000000000000'
imagePullPolicy: IfNotPresent
disableTraefikTls: true
useWorkloadIdentity: true
dnsConfig:
  ndots: "3"
  singleRequestTcp: false
pdb:
  enabled: true
  maxUnavailable: 50%
global:
  enableKeyVaults: false
  devMode: false
  smoketestscron:
    enabled: false
  functionaltestscron:
    enabled: false
prometheus:
  enabled: false
  path: /metrics
ingressClass: traefik
# WARNING: ingressSessionAffinity is a temporary option.
# This is subject to removal without notice. Do NOT use for any reason!
ingressSessionAffinity:
  enabled: false
  sessionCookieName: sticky

# HPA - example
# autoscaling:
#  enabled: true
#  maxReplicas: 5
#  minReplicas: 2
#  targetCPUUtilizationPercentage: 80

autoscaling:
  enabled: true
  cpu:
    enabled: true
    averageUtilization: 80
  memory:
    enabled: true
    averageUtilization: 80

postgresql:
  image:
    tag: '11.16.0'
  ## Whether to deploy the Postgres Chart or not
  enabled: false
## Default Postgres Configuration parameters
  auth:
    username: basepostgres
    password: basepassword
    database: basedatabase
  ## Disable Postgres Persistence
  primary:
    persistence:
      enabled: false

testsConfig:
  memoryRequests: '256Mi'
  cpuRequests: '100m'
  memoryLimits: '2048Mi'
  cpuLimits: '1000m'
  serviceAccountName: tests-service-account
smoketests:
  enabled: false
functionaltests:
  enabled: false
smoketestscron:
  enabled: false
  schedule: "20 0/1 * * *"
functionaltestscron:
  enabled: false
  schedule: "30 0/6 * * *"

#java Overrides
java:
  memoryRequests: '1024Mi'
  cpuRequests: '250m'
  memoryLimits: '2048Mi'
  cpuLimits: '1500m'
  devmemoryRequests: '512Mi'
  devcpuRequests: '250m'
  devmemoryLimits: '1024Mi'
  devcpuLimits: '2500m'
  readinessDelay: 0
  livenessDelay: 0
  startupDelay: 10
  startupFailureThreshold: 20
  devApplicationInsightsInstrumentKeyName: AZURE_APPLICATIONINSIGHTS_INSTRUMENTATIONKEY

#nodejs Overrides
nodejs: 
  devApplicationInsightsInstrumentKeyName: APPINSIGHTS_INSTRUMENTATIONKEY
